# ---------------------------
# INSTALL LIBRARIES
# ---------------------------

install.packages("DBI")
install.packages("odbc")
install.packages("RPostgres")
install.packages("httr")
install.packages("readr")
install.packages("dplyr")
install.packages("lubridate")
install.packages("stringr")
install.packages("tidyverse")
install.packages("ggplot2")
install.packages("rstatix")
install.packages("tibble")
install.packages("tidyr")
install.packages("scales")
install.packages("fastshap")
install.packages("clipr")
install.packages("glue")
install.packages("ggpubr")
install.packages("car")
install.packages("FSA")
install.packages("pwr")
install.packages("RVAideMemoire")
install.packages("lme4")
install.packages("ggeffects")
install.packages("doParallel")
install.packages("randomForest")
install.packages("rpart")
install.packages("rpart.plot")
install.packages("caret")
install.packages("forcats")
install.packages("survival")
install.packages("ranger")
install.packages("mgcv")


# ---------------------------
# LOAD
# ---------------------------
library(DBI)
library(odbc)
library(RPostgres)
library(httr)
library(readr)
library(dplyr)
library(lubridate)
library(stringr)
library(tidyverse)
library(ggplot2)
library(rstatix)
library(tibble)
library(tidyr)
library(parallel)   # base; no install needed
library(scales)
library(stats)      # base; no install needed
library(fastshap)
library(glue)
library(clipr)
library(ggpubr)
library(car)
library(FSA)
library(splines)    # bundled with R; no install needed
library(pwr)
library(RVAideMemoire)
library(lme4)
library(ggeffects)
library(forcats)
library(survival)
library(ranger)
library(doParallel)
library(mgcv)
library(randomForest)
library(rpart)
library(rpart.plot)
library(caret)
